# Generated by Django 5.2.16 on 2026-07-14 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('machinery', '0002_vehicle_make_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='InspectionField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=200, unique=True)),
                ('display_order', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'inspection_fields',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='MachineryInspectionField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.PositiveIntegerField(default=1)),
                ('inspection_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machinery_types', to='inspections.inspectionfield')),
                ('machinery_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspection_fields', to='machinery.machinerytype')),
            ],
            options={
                'db_table': 'machinery_inspection_fields',
                'ordering': ['machinery_type', 'display_order'],
                'unique_together': {('machinery_type', 'inspection_field')},
            },
        ),
    ]
