# Generated by Django 5.2.16 on 2026-07-14 07:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0001_initial'),
        ('machinery', '0002_vehicle_make_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='machineryinspectionfield',
            name='inspection_field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inspections.inspectionfield'),
        ),
        migrations.CreateModel(
            name='InspectionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspection_number', models.CharField(max_length=30, unique=True)),
                ('inspection_date', models.DateField(default=django.utils.timezone.now)),
                ('shift', models.CharField(choices=[('Morning', 'Morning'), ('Evening', 'Evening'), ('Night', 'Night')], max_length=20)),
                ('relay', models.CharField(choices=[('Relay A', 'Relay A'), ('Relay B', 'Relay B'), ('Relay C', 'Relay C'), ('Relay D', 'Relay D'), ('General Shift', 'General Shift')], max_length=30)),
                ('operational_status', models.CharField(choices=[('Fit', 'Fit'), ('Unfit', 'Unfit')], max_length=10)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('engineer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='machinery.vehicle')),
            ],
            options={
                'db_table': 'inspection_logs',
                'ordering': ['-inspection_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InspectionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(choices=[('Pass', 'Pass'), ('Fail', 'Fail')], max_length=10)),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='inspections.inspectionlog')),
                ('inspection_field', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inspections.inspectionfield')),
            ],
            options={
                'db_table': 'inspection_results',
                'unique_together': {('inspection', 'inspection_field')},
            },
        ),
    ]
