# Generated by Django 5.2.16 on 2026-07-22 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0002_alter_machineryinspectionfield_inspection_field_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectionlog',
            name='operator_agency',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='inspectionlog',
            name='operator_checklist_filled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inspectionlog',
            name='operator_employee_id',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='inspectionlog',
            name='operator_mobile',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
        migrations.AddField(
            model_name='inspectionlog',
            name='operator_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
