# Generated by Django 5.2.16 on 2026-07-22 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0003_inspectionlog_operator_agency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectionlog',
            name='operator_remarks',
            field=models.TextField(blank=True, default=''),
        ),
    ]
