# Generated by Django 5.2.16 on 2026-07-22 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0004_inspectionlog_operator_remarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspectionlog',
            name='operator_mobile',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
