# Generated by Django 5.2.16 on 2026-08-21 19:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0005_alter_inspectionlog_operator_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectionlog',
            name='parent_inspection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reinspections', to='inspections.inspectionlog'),
        ),
        migrations.AlterField(
            model_name='inspectionlog',
            name='inspection_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='inspectionlog',
            name='inspection_number',
            field=models.CharField(max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='inspectionlog',
            name='remarks',
            field=models.TextField(blank=True, default=''),
        ),
    ]
