# Generated by Django 5.2.16 on 2026-07-14 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MachineryType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'machinery_types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_number', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Maintenance', 'Maintenance')], default='Active', max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('machinery_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='machinery.machinerytype')),
            ],
            options={
                'db_table': 'vehicles',
                'ordering': ['machine_number'],
            },
        ),
    ]
