# Generated by Django 5.2.16 on 2026-07-14 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machinery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='make_model',
            field=models.CharField(default='unknown', max_length=200),
            preserve_default=False,
        ),
    ]
