CHECKLIST_MAPPING = {

    "Tipper": [
        "First Aid Kit",
        "Seat Belt / Reminder",
        "Brake Light",
        "Rear View Camera",
        "Audio Visual Alarm",
        "Side Mirror",
        "Blind Spot Mirror",
        "Fatigue Alarm",
        "Proximity Warning Device",
        "Dump Body Safety Lock",
        "Battery Cut Off Switch",
        "ROPS / FOPS",
        "AC System",
        "Turbo Guard",
        "Service",
        "Parking",
        "Exhaust Brake",
        "Wiper",
        "Horn",
        "Beacon Light",
        "Propeller Shaft Guard",
        "Mechanical Guard",
        "Dump Body Lifting Position Indicator",
        "Dump Body Stabilisers",
        "Retro Reflective Sticker",
        "Portable Fire Extinguisher",
        "Semi-AFDSS / AFDSS",
        "Auto Dipping",
    ],

    "Excavator": [
        "First Aid Kit",
        "Seat Belt / Reminder",
        "Rear View Camera",
        "Side Mirror",
        "Blind Spot Mirror",
        "Fatigue Alarm",
        "Battery Cut Off Switch",
        "ROPS / FOPS",
        "AC System",
        "Turbo Guard",
        "Wiper",
        "Horn",
        "Beacon Light",
        "Mechanical Guard",
        "Retro Reflective Sticker",
        "Portable Fire Extinguisher",
        "Semi-AFDSS / AFDSS",
    ],

    "Surface Miner": [
        "First Aid Kit",
        "Seat Belt / Reminder",
        "Rear View Camera",
        "Audio Visual Alarm",
        "Side Mirror",
        "Blind Spot Mirror",
        "Fatigue Alarm",
        "Battery Cut Off Switch",
        "ROPS / FOPS",
        "AC System",
        "Turbo Guard",
        "Wiper",
        "Horn",
        "Beacon Light",
        "Retro Reflective Sticker",
        "Portable Fire Extinguisher",
        "Semi-AFDSS / AFDSS",
    ],

    "Dozer": [
        "First Aid Kit",
        "Seat Belt / Reminder",
        "Rear View Camera",
        "Audio Visual Alarm",
        "Side Mirror",
        "Fatigue Alarm",
        "Battery Cut Off Switch",
        "ROPS / FOPS",
        "AC System",
        "Turbo Guard",
        "Wiper",
        "Horn",
        "Beacon Light",
        "Retro Reflective Sticker",
        "Portable Fire Extinguisher",
        "Semi-AFDSS / AFDSS",
    ],

    "Grader": [
        "First Aid Kit",
        "Seat Belt / Reminder",
        "Brake Light",
        "Rear View Camera",
        "Audio Visual Alarm",
        "Side Mirror",
        "Blind Spot Mirror",
        "Fatigue Alarm",
        "Battery Cut Off Switch",
        "ROPS / FOPS",
        "AC System",
        "Turbo Guard",
        "Wiper",
        "Horn",
        "Beacon Light",
        "Retro Reflective Sticker",
        "Portable Fire Extinguisher",
        "Semi-AFDSS / AFDSS",
    ],

    "Wheel Loader": [
        "First Aid Kit",
        "Seat Belt / Reminder",
        "Brake Light",
        "Rear View Camera",
        "Audio Visual Alarm",
        "Side Mirror",
        "Blind Spot Mirror",
        "Fatigue Alarm",
        "Battery Cut Off Switch",
        "ROPS / FOPS",
        "AC System",
        "Turbo Guard",
        "Wiper",
        "Horn",
        "Beacon Light",
        "Retro Reflective Sticker",
        "Portable Fire Extinguisher",
        "Semi-AFDSS / AFDSS",
    ],

    "Water Tanker": [
        "First Aid Kit",
        "Seat Belt / Reminder",
        "Brake Light",
        "Rear View Camera",
        "Audio Visual Alarm",
        "Side Mirror",
        "Blind Spot Mirror",
        "Fatigue Alarm",
        "Proximity Warning Device",
        "Battery Cut Off Switch",
        "ROPS / FOPS",
        "AC System",
        "Turbo Guard",
        "Service",
        "Parking",
        "Exhaust Brake",
        "Wiper",
        "Horn",
        "Beacon Light",
        "Propeller Shaft Guard",
        "Mechanical Guard",
        "Retro Reflective Sticker",
        "Portable Fire Extinguisher",
        "Semi-AFDSS / AFDSS",
    ],

    "Diesel Tanker": [
        "First Aid Kit",
        "Seat Belt / Reminder",
        "Brake Light",
        "Rear View Camera",
        "Audio Visual Alarm",
        "Side Mirror",
        "Blind Spot Mirror",
        "Fatigue Alarm",
        "Proximity Warning Device",
        "Battery Cut Off Switch",
        "ROPS / FOPS",
        "AC System",
        "Turbo Guard",
        "Service",
        "Parking",
        "Exhaust Brake",
        "Wiper",
        "Horn",
        "Beacon Light",
        "Propeller Shaft Guard",
        "Mechanical Guard",
        "Retro Reflective Sticker",
        "Portable Fire Extinguisher",
        "Semi-AFDSS / AFDSS",
    ],

    "Service Van": [
        "First Aid Kit",
        "Seat Belt / Reminder",
        "Brake Light",
        "Rear View Camera",
        "Audio Visual Alarm",
        "Side Mirror",
        "Blind Spot Mirror",
        "Fatigue Alarm",
        "Proximity Warning Device",
        "Battery Cut Off Switch",
        "ROPS / FOPS",
        "AC System",
        "Turbo Guard",
        "Service",
        "Parking",
        "Exhaust Brake",
        "Wiper",
        "Horn",
        "Beacon Light",
        "Propeller Shaft Guard",
        "Mechanical Guard",
        "Retro Reflective Sticker",
        "Portable Fire Extinguisher",
        "Semi-AFDSS / AFDSS",
    ],

    "Crane": [
        "First Aid Kit",
        "Seat Belt / Reminder",
        "Brake Light",
        "Rear View Camera",
        "Side Mirror",
        "Battery Cut Off Switch",
        "ROPS / FOPS",
        "Turbo Guard",
        "Wiper",
        "Horn",
        "Beacon Light",
        "Retro Reflective Sticker",
        "Portable Fire Extinguisher",
        "Semi-AFDSS / AFDSS",
    ],

    "Drill Machine": [
        "First Aid Kit",
        "Seat Belt / Reminder",
        "Rear View Camera",
        "Audio Visual Alarm",
        "Side Mirror",
        "Blind Spot Mirror",
        "Fatigue Alarm",
        "Battery Cut Off Switch",
        "ROPS / FOPS",
        "AC System",
        "Turbo Guard",
        "Wiper",
        "Horn",
        "Beacon Light",
        "Retro Reflective Sticker",
        "Portable Fire Extinguisher",
        "Semi-AFDSS / AFDSS",
    ],

    "Tower Light": [
        "Retro Reflective Sticker",
    ],
"Bus": [
    "Driving License with validity",
    "Proper PPE for Driver",
    "Pollution Certificate",
    "Vehicle Insurance & Registration Validity",
    "Last Service Report with Date",
    "Brakes Condition",
    "Steering Condition",
    "Beacon Light",
    "Fire Extinguisher",
    "Audio Visual Alarm (AVA)",
    "Rear View Camera",
    "Front Head Lights",
    "Rear Head Lights (Brake Lights)",
    "Retro Reflective Reflectors on Body",
    "Seat Belts (All Seats)",
    "Seat Belt Audible Reminder",
    "Wiper & Water Spray",
    "Windshield (Clean & Clear)",
    "Horn",
    "Rear View Mirror - Left",
    "Rear View Mirror - Right",
    "Working Air Conditioning",
    "First Aid Kit",
    "Any Other Remarks",
],

}